{{- $dot := . }}
{{- range .Values.versions }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    chart: {{ template "helm-nginx.chart" $dot }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        release: {{ $.Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $dot | sha256sum }}  
    spec:
      containers:
      - name: {{ .name }}
        image: "{{ .image.repository }}"
        imagePullPolicy: {{ .image.pullPolicy }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/    
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumes:
        - name: config-volume
          configMap:
            name: {{ .name }}-ConfigMap
{{ toYaml $.Values.resources | indent 12 }}
    {{- with $.Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with $.Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

{{ end }}

