{{- $dot := . }}
{{- range .Values.versions }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    chart: {{ template "helm-nginx.chart" $dot }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "helm-nginx.name" $dot }}
    release: {{ $.Release.Name }}
{{ end }}